---
- name: Install Web Software on RHEL VM
  hosts: all
  gather_facts: True

  roles:
    - { common, when: websoftware is defined }
    - { common_lamp, when: websoftware == 'httpd' }
    - { common_wp, when: websoftware == 'nginx' }
    - { web, when: websoftware == 'httpd' }  
    - { nginx, when: websoftware == 'nginx' }
  
