---
- name: Install DB Software on RHEL VM
  hosts: all
  gather_facts: True

  roles:
    - { common, when: dbsoftware is defined }
    - { common_lamp, when: dbsoftware == 'mariadb' }
    - { db, when: dbsoftware == 'mariadb' }  
    - { ansible-postgresql, when: dbsoftware == 'postgresql' }
