---
- name: Download a clean default.conf
  get_url: url=http://10.15.39.100/files/default.conf dest=/etc/nginx/conf.d/default.conf
  
- name: Restart NGINX service
  service: name=nginx state=restarted
